### ISSUE TITLE
OpenSpeedTest on Synology  shows Network Error

### ISSUE THREAD

**Issue by astronyu** [michellabbe/docker-openspeedtest#5]
Hello, I tried running this on Synology based on multiple guide videos on youtube. It installed fine however I kept getting the Network Error message when trying to start the test.

Can anyone help me with this?

Thank you.

**Comment by sebastien-k** [comment]
Hello, same issue.

> Hello, I tried running this on Synology based on multiple guide videos on youtube. It installed fine however I kept getting the Network Error message when trying to start the test.
> 
> Can anyone help me with this?
> 
> Thank you.

**Comment by michellabbe** [comment]
Same error here, and also on ubuntu.

To be honest, I haven't been using this image myself for a while now.
This is an old iframe version of openspeedtest, I'm guessing the code it used from openspeedtest website got killed.

There is no point in maintaning this image now that there is an official one (without iframe).
Use the official [OpenSpeedtest](https://hub.docker.com/r/openspeedtest/latest) Docker image instead.
